version: "3.7"

services:
  db:
    image: linuxserver/mariadb
    container_name: librebooking-db
    restart: always
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - vol-db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=
      - MYSQL_DATABASE=librebooking
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=lb_user
      - MYSQL_PASSWORD=
  app:
    image: colisee/librebooking
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8080:80"
    volumes:
      - vol-app:/var/www/html
    environment: 
      - TZ=
      - LB_DB_HOST=lb-db
      - LB_DB_NAME=librebooking
      - LB_INSTALL_PWD=
      - LB_DB_USER=lb_user
      - LB_DB_USER_PWD=

volumes:
  vol-db:
    name: librebooking-db_data
  vol-app:
    name: librebooking_html

networks:
  net:
    name: librebooking
